apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-demo-app
  template:
    metadata:
      labels:
        app: azure-demo-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-demo-app
        image: acsrameshcontainerregistry1.azurecr.io/azure-demo-app:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: azure-demo-app
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app: azure-demo-app